### ISSUE TITLE
Exécution en ligne de commande

### ISSUE THREAD

**Issue by Bludwarf** [Bludwarf/gangsta-socca#14]
Actuellement il est nécessaire de pouvoir afficher des fenêtres pour répondre à des questions (joueur inconnu, mail manquant) ce qui rend son exécution impossible en ligne de commande.

**Comment by Bludwarf** [comment]
Exemple d'erreur quand le programme souhaite ouvrir le mail HTML dans le navigateur par défaut :

```
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.Desktop.getDesktop(Desktop.java:142)
        at fr.bludwarf.gangstasocca.Main.main(Main.java:50)
```
